package dev.tacticaltacz;
/** Release-pinned native state; preserves native Minecraft damage units on unclaimed targets. */
public record ContinuationState(
    int life,
    float speed,
    float gravity,
    float friction,
    java.util.LinkedList<com.tacz.guns.resource.pojo.data.gun.ExtraDamage.DistanceDamagePair> damageAmount,
    float distanceAmount,
    float knockback,
    boolean explosion,
    boolean igniteEntity,
    boolean igniteBlock,
    int igniteEntityTime,
    float explosionDamage,
    float explosionRadius,
    int explosionDelayCount,
    boolean explosionKnockback,
    boolean explosionDestroyBlock,
    float damageModifier,
    int pierce,
    net.minecraft.world.phys.Vec3 startPos,
    boolean isTracerAmmo,
    float cameraXRot,
    float cameraYRot,
    org.joml.Vector3f firstPersonRenderOffset,
    net.minecraft.resources.ResourceLocation ammoId,
    net.minecraft.resources.ResourceLocation gunId,
    net.minecraft.resources.ResourceLocation gunDisplayId,
    float armorIgnore,
    float headShot,
    float shotDamageMultiplier,
    double damageScale) {}
