modLoader = "javafml"
loaderVersion = "[1,)"
logoFile = "logo.png"
authors = "Serene Wave Studio | Timeless Squad"
license = "GPL3 / CC BY-NC-ND 4.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''
'''

[[mixins]]
config = "tacz.mixins.json"

[[mixins]]
config = "tacz.compat.acceleratedrendering.mixins.json"

[[mixins]]
config = "tactical_tacz_adapter.mixins.json"

[[dependencies."${id}"]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${loader_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "item_foundation"
type = "required"
versionRange = "[0.0.0-dev]"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${id}"]]
modId = "ldlib2"
type = "required"
versionRange = "[2.2.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${id}"]]
modId = "tactical_inventory"
type = "required"
versionRange = "[0.0.0-dev]"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${id}"]]
modId = "tactical_character"
type = "required"
versionRange = "[0.0.0-dev]"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${id}"]]
modId = "tactical_combat"
type = "required"
versionRange = "[0.0.0-dev]"
ordering = "AFTER"
side = "BOTH"
