(()=>{'use strict';
const $=id=>document.getElementById(id),S={catalog:null,data:null,selection:null,selected:'',yaw:-.23,pitch:-.12,zoom:1,drag:null,program:null,buffer:null};
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const v=await r.json();if(!r.ok)throw Error(v.error||r.statusText);return v}
function options(id,rows,value){const el=$(id),wanted=value??el.value;el.replaceChildren(...rows.map(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=r.name||r.id;return o}));if([...el.options].some(o=>o.value===wanted))el.value=wanted}
function vec(a){return a?.map(v=>Number(v).toFixed(3)).join(', ')||'—'}
async function boot(){try{const st=await api('/api/status');$('identity').textContent=st.project;$('status').textContent=st.state==='ready'?'输入就绪':st.error||st.state;$('status').className='status '+st.state;if(st.state!=='ready'){setTimeout(boot,1500);return}S.catalog=await api('/api/catalog');options('weapon',S.catalog.weapons);await load(true)}catch(e){$('status').textContent=e.message;$('status').className='status failed';setTimeout(boot,2500)}}
async function load(reset=false,edit=null){try{$('message').textContent='正在读取共享装配与几何…';const body={weapon:$('weapon').value};if(!reset&&S.selection)body.selection=S.selection;if(edit)body.edit=edit;S.data=await api('/api/assembly',body);S.selection=S.data.selection;describe();buildScene();fit();$('message').textContent='拖拽旋转 · 滚轮缩放 · 点击右侧节点查看坐标'}catch(e){$('message').textContent='载入失败：'+e.message}}
function describe(){const d=S.data;options('slot',d.slots.map(x=>({id:x.path,name:(x.required?'* ':'')+x.path})));describeSlot();$('validation').textContent=d.validation.complete?'完整':d.validation.valid?'结构有效，但缺少必需部件':'装配无效';$('recipe').textContent=`${d.weapon} · ${d.parts.length} 个节点 · ${d.nativeRig?'TaCZ 原生骨骼来源':'独立装配模型'}`;const box=$('parts');box.replaceChildren(...d.parts.map(p=>{const b=document.createElement('button');b.className='part'+(p.path===S.selected?' active':'');b.innerHTML=`${p.definition}<small>${p.path||'ROOT'}</small>`;b.onclick=()=>{S.selected=p.path;describePart();describe()};return b}));describePart()}
function describeSlot(){const row=S.data?.slots.find(x=>x.path===$('slot').value);if(!row)return;options('candidate',row.candidates,row.installed);$('slot-detail').textContent=`当前：${row.installed||'空槽'}${row.worldAnchor?' · 锚点 '+vec(row.worldAnchor):''}`;$('remove').disabled=!row.installed}
function describePart(){const p=S.data?.parts.find(x=>x.path===S.selected)||S.data?.parts[0];if(!p)return;S.selected=p.path;$('node').textContent=p.definition;$('origin').textContent=vec(p.origin);$('attachment-origin').textContent=vec(p.attachmentOrigin)}
function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function initGL(){const gl=$('scene').getContext('webgl',{antialias:true,preserveDrawingBuffer:true});if(!gl)throw Error('浏览器不支持 WebGL');const vs=shader(gl,gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 c;uniform vec3 center;uniform float yaw,pitch,scale,aspect,pointSize;varying vec3 color;void main(){vec3 q=p-center;float cy=cos(yaw),sy=sin(yaw),cp=cos(pitch),sp=sin(pitch);q=vec3(q.x*cy+q.z*sy,q.y,-q.x*sy+q.z*cy);q=vec3(q.x,q.y*cp-q.z*sp,q.y*sp+q.z*cp);gl_Position=vec4(q.x*scale/aspect,q.y*scale,-q.z*.002,1.);gl_PointSize=pointSize;color=c;}`);const fs=shader(gl,gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 color;void main(){gl_FragColor=vec4(color,1.);}`);const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);S.gl=gl;S.program=program;S.buffer=gl.createBuffer();S.anchorBuffer=gl.createBuffer()}
function buildScene(){if(!S.gl)initGL();const values=[],anchors=[];for(const part of S.data.parts){values.push(...part.vertices);anchors.push(...part.origin,0.1,0.85,1)}S.vertices=new Float32Array(values);S.anchors=new Float32Array(anchors);const gl=S.gl;gl.bindBuffer(gl.ARRAY_BUFFER,S.buffer);gl.bufferData(gl.ARRAY_BUFFER,S.vertices,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,S.anchorBuffer);gl.bufferData(gl.ARRAY_BUFFER,S.anchors,gl.STATIC_DRAW);const xyz=[];for(let i=0;i<S.vertices.length;i+=6)xyz.push([S.vertices[i],S.vertices[i+1],S.vertices[i+2]]);S.min=[0,1,2].map(k=>Math.min(...xyz.map(v=>v[k])));S.max=[0,1,2].map(k=>Math.max(...xyz.map(v=>v[k])));S.center=S.min.map((v,i)=>(v+S.max[i])/2);draw()}
function fit(){if(!S.min)return;const span=Math.max(S.max[0]-S.min[0],S.max[1]-S.min[1],S.max[2]-S.min[2]);S.zoom=1.72/Math.max(span,1);draw()}
function draw(){if(!S.gl||!S.vertices)return;const canvas=$('scene'),ratio=devicePixelRatio||1,w=Math.max(1,canvas.clientWidth*ratio|0),h=Math.max(1,canvas.clientHeight*ratio|0);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const gl=S.gl;gl.viewport(0,0,w,h);gl.clearColor(.025,.07,.085,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.useProgram(S.program);const p=gl.getAttribLocation(S.program,'p'),c=gl.getAttribLocation(S.program,'c');gl.uniform3fv(gl.getUniformLocation(S.program,'center'),S.center);gl.uniform1f(gl.getUniformLocation(S.program,'yaw'),S.yaw);gl.uniform1f(gl.getUniformLocation(S.program,'pitch'),S.pitch);gl.uniform1f(gl.getUniformLocation(S.program,'scale'),S.zoom);gl.uniform1f(gl.getUniformLocation(S.program,'aspect'),w/h);gl.uniform1f(gl.getUniformLocation(S.program,'pointSize'),1);gl.bindBuffer(gl.ARRAY_BUFFER,S.buffer);gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(c);gl.vertexAttribPointer(c,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.TRIANGLES,0,S.vertices.length/6);if($('anchors').checked){gl.disable(gl.CULL_FACE);gl.uniform1f(gl.getUniformLocation(S.program,'pointSize'),8*ratio);gl.bindBuffer(gl.ARRAY_BUFFER,S.anchorBuffer);gl.vertexAttribPointer(p,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(c,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.POINTS,0,S.anchors.length/6)}}
$('weapon').onchange=()=>{S.selection=null;S.selected='';load(true)};$('slot').onchange=describeSlot;$('apply').onclick=()=>load(false,{path:$('slot').value,definition:$('candidate').value});$('remove').onclick=()=>load(false,{path:$('slot').value,definition:''});$('reset').onclick=()=>{S.selection=null;load(true)};$('rebuild').onclick=async()=>{await api('/api/rebuild',{});S.catalog=null;S.data=null;boot()};$('fit').onclick=fit;$('left').onclick=()=>{S.yaw=Math.PI/2;S.pitch=0;draw()};$('side').onclick=()=>{S.yaw=0;S.pitch=0;draw()};$('oblique').onclick=()=>{S.yaw=-.65;S.pitch=-.28;draw()};$('save').onclick=()=>{const a=document.createElement('a');a.download=`tacz-workbench-${$('weapon').value.replace(':','-')}.png`;a.href=$('scene').toDataURL('image/png');a.click()};
const canvas=$('scene');$('anchors').onchange=draw;canvas.onpointerdown=e=>{S.drag=[e.clientX,e.clientY,S.yaw,S.pitch];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!S.drag)return;S.yaw=S.drag[2]+(e.clientX-S.drag[0])*.008;S.pitch=Math.max(-1.45,Math.min(1.45,S.drag[3]+(e.clientY-S.drag[1])*.008));draw()};canvas.onpointerup=()=>S.drag=null;canvas.onwheel=e=>{e.preventDefault();S.zoom*=Math.exp(-e.deltaY*.001);S.zoom=Math.max(.01,Math.min(2,S.zoom));draw()};addEventListener('resize',draw);boot();
})();
